// src/data/foodData.js
const foodData = {
  restaurants: [
    {
      id: 1,
      name: 'Hotel Sandeep',
      imageUrl: 'https://via.placeholder.com/200',
      details: 'Maharashtrian, North Indian, Chinese, Mughlai',
      location: 'JM Road, Pune',
      rating: 4.2,
      reviews: 120,
      time: '29 min',
      priceRange: [200, 800],
      menu: [
        { id: 1, name: 'Veg Biryani', imageUrl: 'https://via.placeholder.com/100', price: 200 },
        { id: 2, name: 'Chicken Biryani', imageUrl: 'https://via.placeholder.com/100', price: 250 },
        { id: 3, name: 'Paneer Butter Masala', imageUrl: 'https://via.placeholder.com/100', price: 150 },
        { id: 4, name: 'Tandoori Roti', imageUrl: 'https://via.placeholder.com/100', price: 50 },
      ],
    },
    {
      id: 2,
      name: 'Burger King',
      imageUrl: 'https://via.placeholder.com/200',
      details: 'Burger, Fast Food, Beverages',
      location: 'MG Road, Pune',
      rating: 4.0,
      reviews: 200,
      time: '39 min',
      priceRange: [300, 1000],
      menu: [
        { id: 1, name: 'Whopper', imageUrl: 'https://via.placeholder.com/100', price: 150 },
        { id: 2, name: 'Chicken Fries', imageUrl: 'https://via.placeholder.com/100', price: 100 },
        { id: 3, name: 'Veggie Burger', imageUrl: 'https://via.placeholder.com/100', price: 120 },
        { id: 4, name: 'Coke', imageUrl: 'https://via.placeholder.com/100', price: 50 },
      ],
    },
    {
      id: 3,
      name: 'KFC',
      imageUrl: 'https://via.placeholder.com/200',
      details: 'Fast Food, Beverages',
      location: 'FC Road, Pune',
      rating: 4.1,
      reviews: 150,
      time: '33 min',
      priceRange: [250, 900],
      menu: [
        { id: 1, name: 'Zinger Burger', imageUrl: 'https://via.placeholder.com/100', price: 180 },
        { id: 2, name: 'Chicken Popcorn', imageUrl: 'https://via.placeholder.com/100', price: 200 },
        { id: 3, name: 'French Fries', imageUrl: 'https://via.placeholder.com/100', price: 80 },
        { id: 4, name: 'Pepsi', imageUrl: 'https://via.placeholder.com/100', price: 50 },
      ],
    },
    {
      id: 4,
      name: 'Subway',
      imageUrl: 'https://via.placeholder.com/200',
      details: 'Healthy Food, Beverages',
      location: 'KP Road, Pune',
      rating: 4.3,
      reviews: 100,
      time: '25 min',
      priceRange: [150, 600],
      menu: [
        { id: 1, name: 'Veggie Delight', imageUrl: 'https://via.placeholder.com/100', price: 120 },
        { id: 2, name: 'Chicken Teriyaki', imageUrl: 'https://via.placeholder.com/100', price: 150 },
        { id: 3, name: 'Tuna Sandwich', imageUrl: 'https://via.placeholder.com/100', price: 140 },
        { id: 4, name: 'Iced Tea', imageUrl: 'https://via.placeholder.com/100', price: 60 },
      ],
    },
    {
      id: 5,
      name: 'Starbucks',
      imageUrl: 'https://via.placeholder.com/200',
      details: 'Coffee, Beverages, Snacks',
      location: 'Camp, Pune',
      rating: 4.5,
      reviews: 300,
      time: '45 min',
      priceRange: [200, 1000],
      menu: [
        { id: 1, name: 'Cappuccino', imageUrl: 'https://via.placeholder.com/100', price: 100 },
        { id: 2, name: 'Espresso', imageUrl: 'https://via.placeholder.com/100', price: 120 },
        { id: 3, name: 'Chocolate Croissant', imageUrl: 'https://via.placeholder.com/100', price: 150 },
        { id: 4, name: 'Blueberry Muffin', imageUrl: 'https://via.placeholder.com/100', price: 130 },
      ],
    },
    {
      id: 6,
      name: 'Starbucks',
      imageUrl: 'https://via.placeholder.com/200',
      details: 'Coffee, Beverages, Snacks',
      location: 'Camp, Pune',
      rating: 4.5,
      reviews: 300,
      time: '45 min',
      priceRange: [200, 1000],
      menu: [
        { id: 1, name: 'Cappuccino', imageUrl: 'https://via.placeholder.com/100', price: 100 },
        { id: 2, name: 'Espresso', imageUrl: 'https://via.placeholder.com/100', price: 120 },
        { id: 3, name: 'Chocolate Croissant', imageUrl: 'https://via.placeholder.com/100', price: 150 },
        { id: 4, name: 'Blueberry Muffin', imageUrl: 'https://via.placeholder.com/100', price: 130 },
      ],
    },
    {
      id: 7,
      name: 'Starbucks',
      imageUrl: 'https://via.placeholder.com/200',
      details: 'Coffee, Beverages, Snacks',
      location: 'Camp, Pune',
      rating: 4.5,
      reviews: 300,
      time: '45 min',
      priceRange: [200, 1000],
      menu: [
        { id: 1, name: 'Cappuccino', imageUrl: 'https://via.placeholder.com/100', price: 100 },
        { id: 2, name: 'Espresso', imageUrl: 'https://via.placeholder.com/100', price: 120 },
        { id: 3, name: 'Chocolate Croissant', imageUrl: 'https://via.placeholder.com/100', price: 150 },
        { id: 4, name: 'Blueberry Muffin', imageUrl: 'https://via.placeholder.com/100', price: 130 },
      ],
    },
  ],
};

export default foodData;
